config/routes.rb
Jksurvey::Application.routes.draw do
  resources :answers

  resources :choices

resources :questions do
    collection do
      get :answer
    end
end

root :to => "questions#index"

resources :questionaires

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	  belongs_to :question
  	  belongs_to :choice
end

app/models/choice.rb
class Choice < ActiveRecord::Base
	  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	acts_as_list
  	has_many :choices
  	validates :question, presence: true
end

app/models/questionaire.rb
class Questionaire < ActiveRecord::Base
	has_many :questions
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::ResourcesController
end

app/controllers/admin/choices_controller.rb
class Admin::ChoicesController < Admin::ResourcesController
end

app/controllers/admin/questionaires_controller.rb
class Admin::QuestionairesController < Admin::ResourcesController
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::ResourcesController
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
end

app/controllers/questionaires_controller.rb
class QuestionairesController < ApplicationController
	def show
		@questionaire = Questionaire.find(params[:id])
		@questions =  @questionaire.questions
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def show
		@question = Question.find(params[:id])
		@choices =  @question.choices
		
		if params[:url]
			session[:url] = params[:url]
		end
		
	end

	def answer

	   @url = session[:url] 
	   session[:url] = @url		
	   @choice = Choice.find(:first, :conditions => { :id => params[:id] })
	   @answer = Answer.create(:question_id => @choice.question_id, :choice_id => @choice.id, :pagename => @url)
	    
	   if Question.last == @choice.question
	     render :action => "thankyou"
	   else
	     question = Question.find(:first, :conditions => { :position => (@choice.question.position + 1) })
	     redirect_to question_path(:id => question.id)
	   end
	end
end

app/helpers/admin/answers_helper.rb
module Admin::AnswersHelper
end

app/helpers/admin/choices_helper.rb
module Admin::ChoicesHelper
end

app/helpers/admin/questionaires_helper.rb
module Admin::QuestionairesHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/questionaires_helper.rb
module QuestionairesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.erb
<div data-role="header">
<div data-role="content">
    <%= link_to "Begin Survey", question_path(Question.find(:first)), "data-role"=>"button"%>
</div>

app/views/questions/show.html.erb
<div class="list-group">
<a class="list-group-item active center"><%= @question.question %> </a>

<% @choices.each_with_index do |c, i| %> 
   <% i = i + 1 %>
        <%= link_to "#{c.choice}", answer_questions_path(:id => c.id, :url => @url), :class => "t-white no-ul more-font-sp list-group-item-info list-group-item center" %>
    <% end %>
</div>

app/views/questions/thankyou.html.erb
<div data-role="header" data-theme="b">
  <a href="/" data-icon="home" rel="external">Home</a>
  <h1>Thank You!</h1>
</div>
 
<div data-role="content">
  <p data-role="content">
    Thanks for answering the survey! Have a Good Day! :)
  </p>
</div>